server:
# address: 127.0.0.1
  port: 8761

spring:
  application:
    name:eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultzone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  